from fastapi import FastAPI


products = [
    {
        "id": 1,
        "name": "Laptop Dell XPS 15",
        "sku": "DELL-XPS15-001",
        "category": "Điện tử",
        "subcategory": "Máy tính xách tay",
        "brand": "Dell",
        "price": 35000000,
        "sale_price": 32000000,
        "cost_price": 25000000,
        "currency": "VND",
        "stock_quantity": 50,
        "min_stock": 5,
        "unit": "cái",
        "weight": 1.86,
        "dimensions": {"length": 34.4, "width": 23.0, "height": 1.8},
        "color": "Bạc",
        "material": "Nhôm",
        "description": "Laptop cao cấp với màn hình OLED 15.6 inch, chip Intel Core i7",
        "tags": ["laptop", "dell", "gaming", "cao cấp"],
        "images": ["dell_xps15_1.jpg", "dell_xps15_2.jpg"],
        "rating": 4.8,
        "review_count": 320,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-01-15",
        "updated_at": "2025-03-10",
        "supplier": "Dell Vietnam",
        "warranty_months": 24,
        "origin": "Mỹ"
    },
    {
        "id": 2,
        "name": "iPhone 15 Pro Max",
        "sku": "APPLE-IP15PM-001",
        "category": "Điện tử",
        "subcategory": "Điện thoại",
        "brand": "Apple",
        "price": 34990000,
        "sale_price": 33500000,
        "cost_price": 27000000,
        "currency": "VND",
        "stock_quantity": 120,
        "min_stock": 10,
        "unit": "cái",
        "weight": 0.221,
        "dimensions": {"length": 15.99, "width": 7.68, "height": 0.83},
        "color": "Titan tự nhiên",
        "material": "Titan",
        "description": "iPhone 15 Pro Max với chip A17 Pro, camera 48MP",
        "tags": ["iphone", "apple", "smartphone", "5G"],
        "images": ["iphone15pm_1.jpg", "iphone15pm_2.jpg"],
        "rating": 4.9,
        "review_count": 850,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-02-01",
        "updated_at": "2025-04-01",
        "supplier": "Apple Vietnam",
        "warranty_months": 12,
        "origin": "Mỹ"
    },
    {
        "id": 3,
        "name": "Samsung Galaxy S24 Ultra",
        "sku": "SAM-S24U-001",
        "category": "Điện tử",
        "subcategory": "Điện thoại",
        "brand": "Samsung",
        "price": 31990000,
        "sale_price": 29990000,
        "cost_price": 23000000,
        "currency": "VND",
        "stock_quantity": 80,
        "min_stock": 8,
        "unit": "cái",
        "weight": 0.232,
        "dimensions": {"length": 16.28, "width": 7.91, "height": 0.86},
        "color": "Titan đen",
        "material": "Titan",
        "description": "Samsung Galaxy S24 Ultra với bút S-Pen, camera 200MP",
        "tags": ["samsung", "galaxy", "android", "5G"],
        "images": ["s24ultra_1.jpg", "s24ultra_2.jpg"],
        "rating": 4.7,
        "review_count": 610,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-02-10",
        "updated_at": "2025-03-20",
        "supplier": "Samsung Vietnam",
        "warranty_months": 12,
        "origin": "Hàn Quốc"
    },
    {
        "id": 4,
        "name": "Sony WH-1000XM5",
        "sku": "SONY-WH1000XM5-001",
        "category": "Âm thanh",
        "subcategory": "Tai nghe",
        "brand": "Sony",
        "price": 8990000,
        "sale_price": 7990000,
        "cost_price": 5500000,
        "currency": "VND",
        "stock_quantity": 200,
        "min_stock": 20,
        "unit": "cái",
        "weight": 0.25,
        "dimensions": {"length": 19.5, "width": 16.5, "height": 7.5},
        "color": "Đen",
        "material": "Nhựa cao cấp",
        "description": "Tai nghe chống ồn hàng đầu thế giới với 30h pin",
        "tags": ["tai nghe", "sony", "noise cancelling", "bluetooth"],
        "images": ["wh1000xm5_1.jpg", "wh1000xm5_2.jpg"],
        "rating": 4.8,
        "review_count": 430,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-01-20",
        "updated_at": "2025-02-15",
        "supplier": "Sony Vietnam",
        "warranty_months": 12,
        "origin": "Nhật Bản"
    },
    {
        "id": 5,
        "name": "iPad Pro M4 12.9 inch",
        "sku": "APPLE-IPADPROM4-001",
        "category": "Điện tử",
        "subcategory": "Máy tính bảng",
        "brand": "Apple",
        "price": 29990000,
        "sale_price": 28500000,
        "cost_price": 22000000,
        "currency": "VND",
        "stock_quantity": 60,
        "min_stock": 5,
        "unit": "cái",
        "weight": 0.682,
        "dimensions": {"length": 28.06, "width": 21.49, "height": 0.65},
        "color": "Xám không gian",
        "material": "Nhôm",
        "description": "iPad Pro với chip M4, màn hình OLED 12.9 inch siêu sắc nét",
        "tags": ["ipad", "apple", "tablet", "M4"],
        "images": ["ipadprom4_1.jpg", "ipadprom4_2.jpg"],
        "rating": 4.9,
        "review_count": 280,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-03-05",
        "updated_at": "2025-04-10",
        "supplier": "Apple Vietnam",
        "warranty_months": 12,
        "origin": "Mỹ"
    },
    {
        "id": 6,
        "name": "Màn hình LG 27UK850-W 4K",
        "sku": "LG-27UK850-001",
        "category": "Điện tử",
        "subcategory": "Màn hình",
        "brand": "LG",
        "price": 12500000,
        "sale_price": 11000000,
        "cost_price": 8000000,
        "currency": "VND",
        "stock_quantity": 35,
        "min_stock": 3,
        "unit": "cái",
        "weight": 6.2,
        "dimensions": {"length": 61.4, "width": 36.8, "height": 20.3},
        "color": "Trắng",
        "material": "Nhựa ABS",
        "description": "Màn hình 27 inch 4K UHD, USB-C, HDR10, IPS panel",
        "tags": ["màn hình", "LG", "4K", "UHD"],
        "images": ["lg27uk850_1.jpg", "lg27uk850_2.jpg"],
        "rating": 4.6,
        "review_count": 190,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-01-10",
        "updated_at": "2025-01-20",
        "supplier": "LG Vietnam",
        "warranty_months": 36,
        "origin": "Hàn Quốc"
    },
    {
        "id": 7,
        "name": "Chuột Logitech MX Master 3S",
        "sku": "LOGI-MXM3S-001",
        "category": "Phụ kiện máy tính",
        "subcategory": "Chuột",
        "brand": "Logitech",
        "price": 2290000,
        "sale_price": 1990000,
        "cost_price": 1200000,
        "currency": "VND",
        "stock_quantity": 300,
        "min_stock": 30,
        "unit": "cái",
        "weight": 0.141,
        "dimensions": {"length": 12.42, "width": 8.42, "height": 5.13},
        "color": "Đen than",
        "material": "Nhựa cao cấp",
        "description": "Chuột không dây cao cấp MX Master 3S, 8000 DPI, im lặng click",
        "tags": ["chuột", "logitech", "wireless", "ergonomic"],
        "images": ["mxmaster3s_1.jpg", "mxmaster3s_2.jpg"],
        "rating": 4.8,
        "review_count": 750,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-01-05",
        "updated_at": "2025-03-01",
        "supplier": "Logitech Vietnam",
        "warranty_months": 24,
        "origin": "Thụy Sĩ"
    },
    {
        "id": 8,
        "name": "Bàn phím cơ Keychron K2 Pro",
        "sku": "KEYC-K2PRO-001",
        "category": "Phụ kiện máy tính",
        "subcategory": "Bàn phím",
        "brand": "Keychron",
        "price": 2190000,
        "sale_price": 1890000,
        "cost_price": 1100000,
        "currency": "VND",
        "stock_quantity": 150,
        "min_stock": 15,
        "unit": "cái",
        "weight": 0.86,
        "dimensions": {"length": 31.5, "width": 11.0, "height": 3.9},
        "color": "Xám",
        "material": "Nhôm + Nhựa",
        "description": "Bàn phím cơ không dây 75%, switch Gateron G Pro Red, đèn RGB",
        "tags": ["bàn phím", "cơ", "keychron", "wireless"],
        "images": ["keychrk2pro_1.jpg", "keychrk2pro_2.jpg"],
        "rating": 4.7,
        "review_count": 420,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-02-15",
        "updated_at": "2025-02-20",
        "supplier": "Keychron Official",
        "warranty_months": 12,
        "origin": "Trung Quốc"
    },
    {
        "id": 9,
        "name": "Ổ cứng SSD Samsung 970 EVO Plus 1TB",
        "sku": "SAM-970EVOP-1TB",
        "category": "Lưu trữ",
        "subcategory": "SSD",
        "brand": "Samsung",
        "price": 2490000,
        "sale_price": 2190000,
        "cost_price": 1500000,
        "currency": "VND",
        "stock_quantity": 250,
        "min_stock": 25,
        "unit": "cái",
        "weight": 0.006,
        "dimensions": {"length": 8.0, "width": 2.2, "height": 0.23},
        "color": "Đen",
        "material": "Bo mạch điện tử",
        "description": "SSD NVMe M.2 tốc độ đọc 3500MB/s, ghi 3300MB/s",
        "tags": ["SSD", "samsung", "NVMe", "M.2"],
        "images": ["sam970evop_1.jpg"],
        "rating": 4.8,
        "review_count": 680,
        "is_active": True,
        "is_featured": False,
        "created_at": "2023-12-01",
        "updated_at": "2025-01-10",
        "supplier": "Samsung Vietnam",
        "warranty_months": 60,
        "origin": "Hàn Quốc"
    },
    {
        "id": 10,
        "name": "Camera GoPro HERO12 Black",
        "sku": "GOPRO-H12B-001",
        "category": "Máy ảnh",
        "subcategory": "Action Camera",
        "brand": "GoPro",
        "price": 11990000,
        "sale_price": 10500000,
        "cost_price": 8000000,
        "currency": "VND",
        "stock_quantity": 40,
        "min_stock": 4,
        "unit": "cái",
        "weight": 0.154,
        "dimensions": {"length": 7.18, "width": 4.94, "height": 3.39},
        "color": "Đen",
        "material": "Nhựa chịu nước",
        "description": "Camera hành trình 5.3K60fps, chống nước 10m, HyperSmooth 6.0",
        "tags": ["camera", "gopro", "action", "4K"],
        "images": ["goproh12_1.jpg", "goproh12_2.jpg"],
        "rating": 4.7,
        "review_count": 350,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-01-25",
        "updated_at": "2025-03-05",
        "supplier": "GoPro Vietnam",
        "warranty_months": 12,
        "origin": "Mỹ"
    },
    {
        "id": 11,
        "name": "Loa Bluetooth JBL Charge 5",
        "sku": "JBL-CHG5-001",
        "category": "Âm thanh",
        "subcategory": "Loa bluetooth",
        "brand": "JBL",
        "price": 3990000,
        "sale_price": 3490000,
        "cost_price": 2200000,
        "currency": "VND",
        "stock_quantity": 180,
        "min_stock": 18,
        "unit": "cái",
        "weight": 0.96,
        "dimensions": {"length": 22.3, "width": 9.6, "height": 9.6},
        "color": "Xanh dương",
        "material": "Nhựa chống nước",
        "description": "Loa bluetooth chống nước IP67, pin 20h, có thể sạc ngoài cho thiết bị",
        "tags": ["loa", "JBL", "bluetooth", "chống nước"],
        "images": ["jblchg5_1.jpg", "jblchg5_2.jpg"],
        "rating": 4.7,
        "review_count": 920,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-01-08",
        "updated_at": "2025-02-10",
        "supplier": "JBL Vietnam",
        "warranty_months": 12,
        "origin": "Mỹ"
    },
    {
        "id": 12,
        "name": "Apple Watch Series 9 45mm",
        "sku": "APPLE-AWS9-45",
        "category": "Đồng hồ thông minh",
        "subcategory": "Smartwatch",
        "brand": "Apple",
        "price": 12990000,
        "sale_price": 11990000,
        "cost_price": 9000000,
        "currency": "VND",
        "stock_quantity": 90,
        "min_stock": 9,
        "unit": "cái",
        "weight": 0.051,
        "dimensions": {"length": 4.5, "width": 3.8, "height": 1.07},
        "color": "Nhôm Midnight",
        "material": "Nhôm",
        "description": "Apple Watch Series 9 với chip S9, Double Tap, màn hình Always-On",
        "tags": ["apple watch", "smartwatch", "wearable", "fitness"],
        "images": ["applewatchs9_1.jpg", "applewatchs9_2.jpg"],
        "rating": 4.8,
        "review_count": 540,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-02-20",
        "updated_at": "2025-04-05",
        "supplier": "Apple Vietnam",
        "warranty_months": 12,
        "origin": "Mỹ"
    },
    {
        "id": 13,
        "name": "Router WiFi 6 ASUS RT-AX88U Pro",
        "sku": "ASUS-RTAX88U-001",
        "category": "Mạng",
        "subcategory": "Router",
        "brand": "ASUS",
        "price": 6490000,
        "sale_price": 5990000,
        "cost_price": 4000000,
        "currency": "VND",
        "stock_quantity": 70,
        "min_stock": 7,
        "unit": "cái",
        "weight": 1.04,
        "dimensions": {"length": 26.2, "width": 16.8, "height": 5.5},
        "color": "Đen",
        "material": "Nhựa ABS",
        "description": "Router WiFi 6 AX6000, 8 anten, AiMesh, AiProtection Pro",
        "tags": ["router", "wifi6", "ASUS", "gaming"],
        "images": ["asusrtax88u_1.jpg"],
        "rating": 4.6,
        "review_count": 280,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-01-12",
        "updated_at": "2025-01-25",
        "supplier": "ASUS Vietnam",
        "warranty_months": 24,
        "origin": "Đài Loan"
    },
    {
        "id": 14,
        "name": "Máy in Canon PIXMA G3020",
        "sku": "CANON-G3020-001",
        "category": "Văn phòng",
        "subcategory": "Máy in",
        "brand": "Canon",
        "price": 4290000,
        "sale_price": 3990000,
        "cost_price": 2800000,
        "currency": "VND",
        "stock_quantity": 45,
        "min_stock": 5,
        "unit": "cái",
        "weight": 3.9,
        "dimensions": {"length": 44.8, "width": 30.6, "height": 13.9},
        "color": "Đen",
        "material": "Nhựa ABS",
        "description": "Máy in phun màu đa năng, bể mực liền, in-scan-copy, WiFi",
        "tags": ["máy in", "canon", "phun màu", "wifi"],
        "images": ["canong3020_1.jpg"],
        "rating": 4.5,
        "review_count": 210,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-01-18",
        "updated_at": "2025-02-05",
        "supplier": "Canon Vietnam",
        "warranty_months": 12,
        "origin": "Nhật Bản"
    },
    {
        "id": 15,
        "name": "Bàn làm việc đứng FlexiSpot E7",
        "sku": "FLEX-E7-001",
        "category": "Nội thất",
        "subcategory": "Bàn làm việc",
        "brand": "FlexiSpot",
        "price": 9990000,
        "sale_price": 8990000,
        "cost_price": 6000000,
        "currency": "VND",
        "stock_quantity": 25,
        "min_stock": 3,
        "unit": "cái",
        "weight": 32.0,
        "dimensions": {"length": 120.0, "width": 60.0, "height": 72.0},
        "color": "Trắng",
        "material": "Thép + Gỗ MDF",
        "description": "Bàn nâng hạ điện động, tải trọng 125kg, điều khiển 4 nhớ",
        "tags": ["bàn", "standing desk", "ergonomic", "văn phòng"],
        "images": ["flexispote7_1.jpg", "flexispote7_2.jpg"],
        "rating": 4.7,
        "review_count": 160,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-03-01",
        "updated_at": "2025-03-15",
        "supplier": "FlexiSpot Vietnam",
        "warranty_months": 60,
        "origin": "Trung Quốc"
    },
    {
        "id": 16,
        "name": "Ghế công thái học Herman Miller Aeron",
        "sku": "HM-AERON-001",
        "category": "Nội thất",
        "subcategory": "Ghế văn phòng",
        "brand": "Herman Miller",
        "price": 45000000,
        "sale_price": 42000000,
        "cost_price": 33000000,
        "currency": "VND",
        "stock_quantity": 15,
        "min_stock": 2,
        "unit": "cái",
        "weight": 21.0,
        "dimensions": {"length": 65.0, "width": 66.0, "height": 107.0},
        "color": "Đen than",
        "material": "Lưới 8Z Pellicle",
        "description": "Ghế công thái học cao cấp, hỗ trợ PostureFit SL, tilt cân bằng",
        "tags": ["ghế", "ergonomic", "herman miller", "văn phòng"],
        "images": ["hmaeron_1.jpg", "hmaeron_2.jpg"],
        "rating": 4.9,
        "review_count": 95,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-02-05",
        "updated_at": "2025-04-01",
        "supplier": "Herman Miller Vietnam",
        "warranty_months": 144,
        "origin": "Mỹ"
    },
    {
        "id": 17,
        "name": "Máy chiếu Epson EB-X51",
        "sku": "EPSON-EBX51-001",
        "category": "Văn phòng",
        "subcategory": "Máy chiếu",
        "brand": "Epson",
        "price": 14500000,
        "sale_price": 13000000,
        "cost_price": 9500000,
        "currency": "VND",
        "stock_quantity": 20,
        "min_stock": 2,
        "unit": "cái",
        "weight": 2.5,
        "dimensions": {"length": 30.2, "width": 23.4, "height": 8.7},
        "color": "Trắng",
        "material": "Nhựa ABS",
        "description": "Máy chiếu XGA 3800 Lumen, HDMI, WiFi optional, tuổi thọ bóng 12000h",
        "tags": ["máy chiếu", "epson", "projector", "hội nghị"],
        "images": ["epsonebx51_1.jpg"],
        "rating": 4.5,
        "review_count": 130,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-01-22",
        "updated_at": "2025-02-01",
        "supplier": "Epson Vietnam",
        "warranty_months": 24,
        "origin": "Nhật Bản"
    },
    {
        "id": 18,
        "name": "Webcam Logitech Brio 4K",
        "sku": "LOGI-BRIO4K-001",
        "category": "Phụ kiện máy tính",
        "subcategory": "Webcam",
        "brand": "Logitech",
        "price": 4990000,
        "sale_price": 4490000,
        "cost_price": 2800000,
        "currency": "VND",
        "stock_quantity": 100,
        "min_stock": 10,
        "unit": "cái",
        "weight": 0.063,
        "dimensions": {"length": 10.2, "width": 2.8, "height": 3.0},
        "color": "Đen",
        "material": "Nhựa",
        "description": "Webcam 4K Ultra HD, HDR, nhận diện khuôn mặt Windows Hello",
        "tags": ["webcam", "logitech", "4K", "streaming"],
        "images": ["logibrio4k_1.jpg"],
        "rating": 4.6,
        "review_count": 390,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-01-30",
        "updated_at": "2025-03-10",
        "supplier": "Logitech Vietnam",
        "warranty_months": 36,
        "origin": "Thụy Sĩ"
    },
    {
        "id": 19,
        "name": "Ổ cứng di động WD My Passport 2TB",
        "sku": "WD-MYPASS-2TB",
        "category": "Lưu trữ",
        "subcategory": "Ổ cứng di động",
        "brand": "Western Digital",
        "price": 1890000,
        "sale_price": 1690000,
        "cost_price": 1100000,
        "currency": "VND",
        "stock_quantity": 300,
        "min_stock": 30,
        "unit": "cái",
        "weight": 0.13,
        "dimensions": {"length": 11.0, "width": 6.6, "height": 1.15},
        "color": "Đỏ",
        "material": "Nhựa",
        "description": "Ổ cứng di động 2TB, USB 3.0, mã hóa 256-bit, tự động backup",
        "tags": ["ổ cứng", "WD", "portable", "backup"],
        "images": ["wdmypass_1.jpg"],
        "rating": 4.5,
        "review_count": 520,
        "is_active": True,
        "is_featured": False,
        "created_at": "2023-12-10",
        "updated_at": "2025-01-15",
        "supplier": "WD Vietnam",
        "warranty_months": 36,
        "origin": "Mỹ"
    },
    {
        "id": 20,
        "name": "Máy scan Fujitsu ScanSnap iX1600",
        "sku": "FUJI-IX1600-001",
        "category": "Văn phòng",
        "subcategory": "Máy scan",
        "brand": "Fujitsu",
        "price": 12900000,
        "sale_price": 11500000,
        "cost_price": 8500000,
        "currency": "VND",
        "stock_quantity": 18,
        "min_stock": 2,
        "unit": "cái",
        "weight": 2.8,
        "dimensions": {"length": 29.2, "width": 15.9, "height": 15.8},
        "color": "Trắng",
        "material": "Nhựa ABS",
        "description": "Máy scan 2 mặt tự động 40 trang/phút, WiFi, màn hình cảm ứng",
        "tags": ["scan", "fujitsu", "document", "wifi"],
        "images": ["fujiix1600_1.jpg"],
        "rating": 4.7,
        "review_count": 85,
        "is_active": True,
        "is_featured": False,
        "created_at": "2024-02-08",
        "updated_at": "2025-02-20",
        "supplier": "Fujitsu Vietnam",
        "warranty_months": 12,
        "origin": "Nhật Bản"
    },
    {
        "id": 21,
        "name": "Điều hòa Daikin FTKB35UVMV 1.5HP",
        "sku": "DAIK-FTKB35-001",
        "category": "Điện gia dụng",
        "subcategory": "Điều hòa",
        "brand": "Daikin",
        "price": 10990000,
        "sale_price": 9990000,
        "cost_price": 7500000,
        "currency": "VND",
        "stock_quantity": 30,
        "min_stock": 3,
        "unit": "bộ",
        "weight": 28.0,
        "dimensions": {"length": 78.0, "width": 28.5, "height": 29.0},
        "color": "Trắng",
        "material": "Nhựa ABS",
        "description": "Điều hòa inverter 1.5HP, tiết kiệm điện class A++, lọc không khí",
        "tags": ["điều hòa", "daikin", "inverter", "tiết kiệm điện"],
        "images": ["daikftkb35_1.jpg"],
        "rating": 4.7,
        "review_count": 480,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-03-10",
        "updated_at": "2025-04-15",
        "supplier": "Daikin Vietnam",
        "warranty_months": 36,
        "origin": "Nhật Bản"
    },
    {
        "id": 22,
        "name": "Tủ lạnh Samsung RS64R5101B4 617L",
        "sku": "SAM-RS64R-001",
        "category": "Điện gia dụng",
        "subcategory": "Tủ lạnh",
        "brand": "Samsung",
        "price": 28990000,
        "sale_price": 25990000,
        "cost_price": 19000000,
        "currency": "VND",
        "stock_quantity": 12,
        "min_stock": 2,
        "unit": "cái",
        "weight": 113.0,
        "dimensions": {"length": 91.2, "width": 71.6, "height": 177.8},
        "color": "Đen Than",
        "material": "Thép không gỉ",
        "description": "Tủ lạnh Side by Side 617L, ngăn đông mềm, làm đá tự động, WiFi",
        "tags": ["tủ lạnh", "samsung", "side by side", "inverter"],
        "images": ["samrs64r_1.jpg", "samrs64r_2.jpg"],
        "rating": 4.6,
        "review_count": 230,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-02-25",
        "updated_at": "2025-03-20",
        "supplier": "Samsung Vietnam",
        "warranty_months": 24,
        "origin": "Hàn Quốc"
    },
    {
        "id": 23,
        "name": "Máy giặt LG FV1450H2B 15kg",
        "sku": "LG-FV1450H2B-001",
        "category": "Điện gia dụng",
        "subcategory": "Máy giặt",
        "brand": "LG",
        "price": 22990000,
        "sale_price": 19990000,
        "cost_price": 15000000,
        "currency": "VND",
        "stock_quantity": 20,
        "min_stock": 2,
        "unit": "cái",
        "weight": 72.0,
        "dimensions": {"length": 60.0, "width": 66.5, "height": 85.0},
        "color": "Đen",
        "material": "Thép không gỉ",
        "description": "Máy giặt sấy 15/8kg, AI DD, ThinQ WiFi, hơi nước khử khuẩn",
        "tags": ["máy giặt", "LG", "inverter", "wifi"],
        "images": ["lgfv1450_1.jpg"],
        "rating": 4.7,
        "review_count": 310,
        "is_active": True,
        "is_featured": True,
        "created_at": "2024-03-05",
        "updated_at": "2025-04-01",
        "supplier": "LG Vietnam",
        "warranty_months": 24,
        "origin": "Hàn Quốc"
    }
]

app = FastAPI()

@app.get("/health")
def health():
    return {"status": "ok", "message": "Service is running"}


@app.get("/products/{product_name}")
def get_product_by_name(product_name: str):
    for product in products:
        if product["name"] == product_name:
            return {
                "status": "success",
                "data": product
            }
            
    return {
        "status": "success",
        "data": {}
    }

@app.get("/product")
def get_products_by_category(q: str):
    print(q)